# Generated by Django 3.0.4 on 2020-03-26 12:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('pizza', '0002_auto_20200326_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
